server:
  port: 10086

spring:
  application:
    name: spring-cloud-config-server

## config.server git
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/yqjdcyy/Hello_Spring_Cloud_Config

## config.server locale
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: D:/work/git/yao/java/Hello_Spring_Cloud_Config

## Eureka.Register.*
#      discovery:
#        enabled: true
#        service-id: config-server

## Bus.Kafka
#    stream:
#      kafka:
#        binder:
#          brokers: "192.168.16.37:9092"

## bus.mq
#  activemq:
#    host: 192.168.16.37
#    port: 7200

## Actuator.*
management:
  endpoints:
    web:
      exposure:
        include: "*"

## Eureka.*
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka

