server:
  port: 10086
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yqjdcyy/Hello_Spring_Cloud_Config
#          search-paths: config-repo
#          username:
#          password:
  activemq:
    host: 192.168.16.37
    port: 7200
#    username: admin
#    password: admin

management:
  endpoint:
    refresh:
      enabled: true